config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :contacts
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.all
  end
  
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    
    if @contact.save
      redirect_to @contact
    else 
      render 'new'
    end
  end
  
  def show
        @contact = Contact.find(params[:id])
  end
  
  def destroy
      @contact = Contact.find(params[:id])
      @contact.destroy
      redirect_to contacts_home_url
  end
    
  def edit
      @contact = Contact.find(params[:id])
  end
  
  def update
      @contact = Contact.find(params[:id])
      if @contact.update(contact_params)
          redirect_to @contact
      else
          render 'edit'
      end
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :address, :note)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else 
      render 'new'
    end
  end
  
  def show
        @user = User.find(params[:id])
  end
  
  def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to users_path
  end
    
  def edit
      @user = User.find(params[:id])
  end
  
  def update
      @user = User.find(params[:id])
      if @user.update(user_params)
          redirect_to @user
      else
          render 'edit'
      end
  end
  
  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/home.html.erb
<body>
<center>

<header class="sticky">
  <table class="headerNav">
    <tr>
      <td class="headerLeft">
        <%= link_to 'Create New Contact', contacts_new_url, class: "btn", style: "height:15px;width:150px" %>
      </td>
      <td class="headerMid">
      <h1 class="title"> Contacts List</h1>
      </td>
      <td class="headerRight">
        <%= link_to "Sign out", signout_path, id: "sign_out", class: "btn", style: "height:15px;width:150px" %>
      </td>
    </tr>

  </table>
</header>

<div class="contactContainer">
<h2>Contacts</h2>
<td>
  <tr>
    <tc>
      <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search..">
    </tc>
  </tr>
</td>
<ul id="myUL">
  <table id ="myTable">
<% current_user.contacts.order("name ASC").each do |contact| %>
  <li>
      <tr>
        <p>
          <td class="nameColumn">
            <strong>Name:</strong>
            <%= contact.name %>
          </td>
    
          <td class="emailColumn">
            <strong>Email:</strong>
            <%= contact.email %>
          </td>
     
          <td class="showColumn"><%= link_to 'Show', contact_path(contact) , class: "btn"%></td>
          <td class="editColumn"><%= link_to 'Edit', edit_contact_path(contact), class: "btn"%></td>
          <td class="deleteColumn"><%= link_to 'Delete', [contact.user, contact],
                method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn"%></td>
        </p>
      </tr>
  </li>
<% end %>
</table>
</ul>
</center>
</div>
</body>

app/views/contacts/index.html.erb
<body>
<center>
<h1 class="title">Contacts List</h1>

<div class="contactContainer">
<h2>Contacts</h2>
<td>
  <tr>
    <tc>
      <button>
      <%= link_to 'Create New Contact', new_contact_path %>
      </button>
    </tc>
    <tc>
      <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search..">
    </tc>
  </tr>
</td>
<ul id="myUL">
<% @contact.order("name ASC").each do |contact| %>
  <li>
    <p>
    <strong>Name:</strong>
    <%= contact.name %>
    ||
    <strong>Email:</strong>
    <%= contact.email %>
    
    ||
     
      <td><%= link_to 'Show', contact_path(contact) %></td>
      ||
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      ||
      <td><%= link_to 'Delete', [contact.user, contact],
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </li>
<% end %>
</p>
</ul>
</center>
</body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AddressBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Editing contact</h1>
 
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
<p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<body>
<center>
<h1 class="title">Contacts List</h1>

<div class="contactContainer">
<h2>Contacts</h2>
<td>
  <tr>
    <tc>
      <button>
      <%= link_to 'Create New Contact', new_user_path %>
      </button>
    </tc>
    <tc>
      <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search..">
    </tc>
  </tr>
</td>
<ul id="myUL">
<% @user.order("name ASC").each do |user| %>
  <li>
    <p>
    <strong>Name:</strong>
    <%= user.name %>
    ||
     
      <td><%= link_to 'Show', user_path(user) %></td>
      ||
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      ||
      <td><%= link_to 'Delete', user_path(user),
              method: :delete %></td>
    </tr>
    </li>
<% end %>
</p>
</ul>
</center>
</body>
</div>

app/views/users/new.html.erb
<h1>Add a New User</h1>
<%= form_for @user do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.submit %>
    </p>
    <p>
        <%= link_to 'Back', new_user_path %>
    </p>
<% end %>

app/views/users/provideInfo.html.erb
<h1>Add a New Contact</h1>
<%= form_for([current_user, current_user.contacts.build]) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    </p>
    <p>
        <%= f.label :phone %><br>
        <%= f.text_field :phone %>
    </p>
    <p>
        <%= f.label :address %><br>
        <%= f.text_field :address %>
    </p>
    <p>
        <%= f.label :note %><br>
        <%= f.text_area :note %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<%= link_to 'Users List', users_path %>

app/views/welcome/index.html.erb
<h1>Address Book</h1>

<center>
<%= image_tag("contacts4.png", :alt => "Contacts Image", :class => "contact_Pic") %>
</center>

<%= link_to 'My Users', controller: 'users' %>